*mata mata drop loadcty()
mata: 
void function loadcty() {
external hl_cty
hl_cty = asarray_create()
asarray(hl_cty, "Afghanistan","004")
asarray(hl_cty, "Albania","008")
asarray(hl_cty, "Antarctica","010")
asarray(hl_cty, "Algeria","012")
asarray(hl_cty, "American Samoa","016")
asarray(hl_cty, "Andorra","020")
asarray(hl_cty, "Angola","024")
asarray(hl_cty, "Antigua and Barbuda","028")
asarray(hl_cty, "Azerbaijan","031")
asarray(hl_cty, "Argentina","032")
asarray(hl_cty, "Australia","036")
asarray(hl_cty, "Austria","040")
asarray(hl_cty, "The Bahamas","044")
asarray(hl_cty, "Bahrain","048")
asarray(hl_cty, "Bangladesh","050")
asarray(hl_cty, "Armenia","051")
asarray(hl_cty, "Barbados","052")
asarray(hl_cty, "Belgium","056")
asarray(hl_cty, "Bermuda","060")
asarray(hl_cty, "Bhutan","064")
asarray(hl_cty, "Bolivia","068")
asarray(hl_cty, "Bosnia and Herzegovina","070")
asarray(hl_cty, "Botswana","072")
asarray(hl_cty, "Brazil","076")
asarray(hl_cty, "British Antarctic Territory","080")
asarray(hl_cty, "Belize","084")
asarray(hl_cty, "Solomon Islands","090")
asarray(hl_cty, "British Virgin Islands","092")
asarray(hl_cty, "Brunei","096")
asarray(hl_cty, "Bulgaria","100")
asarray(hl_cty, "Myanmar","104")
asarray(hl_cty, "Burundi","108")
asarray(hl_cty, "Belarus","112")
asarray(hl_cty, "Cambodia","116")
asarray(hl_cty, "Cameroon","120")
asarray(hl_cty, "Canada","124")
asarray(hl_cty, "Cabo Verde","132")
asarray(hl_cty, "Cayman Islands","136")
asarray(hl_cty, "Central African Republic","140")
asarray(hl_cty, "Sri Lanka","144")
asarray(hl_cty, "Chad","148")
asarray(hl_cty, "Chile","152")
asarray(hl_cty, "China","156")
asarray(hl_cty, "Taiwan","158")
asarray(hl_cty, "Christmas Island","162")
asarray(hl_cty, "Cocos (Keeling) Islands","166")
asarray(hl_cty, "Colombia","170")
asarray(hl_cty, "Comoros","174")
asarray(hl_cty, "Republic of the Congo","178")
asarray(hl_cty, "Democratic Republic of the Congo","180")
asarray(hl_cty, "Cook Islands","184")
asarray(hl_cty, "Costa Rica","188")
asarray(hl_cty, "Croatia","191")
asarray(hl_cty, "Cuba","192")
asarray(hl_cty, "Cyprus","196")
asarray(hl_cty, "Czechoslovakia","200")
asarray(hl_cty, "Benin","204")
asarray(hl_cty, "Denmark","208")
asarray(hl_cty, "Dominica","212")
asarray(hl_cty, "Dominican Republic","214")
asarray(hl_cty, "Ecuador","218")
asarray(hl_cty, "El Salvador","222")
asarray(hl_cty, "Equatorial Guinea","226")
asarray(hl_cty, "Ethiopia","231")
asarray(hl_cty, "Eritrea","232")
asarray(hl_cty, "Estonia","233")
asarray(hl_cty, "Faroe Islands","234")
asarray(hl_cty, "Falkland Islands","238")
asarray(hl_cty, "South Georgia and the South Sandwich Islands","239")
asarray(hl_cty, "Fiji","242")
asarray(hl_cty, "Finland","246")
asarray(hl_cty, "Aland Islands","248")
asarray(hl_cty, "France","250")
asarray(hl_cty, "French Guiana","254")
asarray(hl_cty, "Djibouti","262")
asarray(hl_cty, "Gabon","266")
asarray(hl_cty, "Georgia (country)","268")
asarray(hl_cty, "The Gambia","270")
asarray(hl_cty, "State of Palestine","275")
asarray(hl_cty, "Germany","276")
asarray(hl_cty, "Ghana","288")
asarray(hl_cty, "Gibraltar","292")
asarray(hl_cty, "Greece","300")
asarray(hl_cty, "Greenland","304")
asarray(hl_cty, "Grenada","308")
asarray(hl_cty, "Guadeloupe","312")
asarray(hl_cty, "Guam","316")
asarray(hl_cty, "Guatemala","320")
asarray(hl_cty, "Guinea","324")
asarray(hl_cty, "Guyana","328")
asarray(hl_cty, "Haiti","332")
asarray(hl_cty, "Vatican City","336")
asarray(hl_cty, "Honduras","340")
asarray(hl_cty, "Hong Kong","344")
asarray(hl_cty, "Hungary","348")
asarray(hl_cty, "Iceland","352")
asarray(hl_cty, "India","356")
asarray(hl_cty, "Indonesia","360")
asarray(hl_cty, "Iran","364")
asarray(hl_cty, "Iraq","368")
asarray(hl_cty, "Republic of Ireland","372")
asarray(hl_cty, "Israel","376")
asarray(hl_cty, "Italy","380")
asarray(hl_cty, "CA'te d'Ivoire","384")
asarray(hl_cty, "Jamaica","388")
asarray(hl_cty, "Japan","392")
asarray(hl_cty, "Johnston Atoll","396")
asarray(hl_cty, "Kazakhstan","398")
asarray(hl_cty, "Jordan","400")
asarray(hl_cty, "Kenya","404")
asarray(hl_cty, "North Korea","408")
asarray(hl_cty, "South Korea","410")
asarray(hl_cty, "Kuwait","414")
asarray(hl_cty, "Kyrgyzstan","417")
asarray(hl_cty, "Laos","418")
asarray(hl_cty, "Lebanon","422")
asarray(hl_cty, "Lesotho","426")
asarray(hl_cty, "Latvia","428")
asarray(hl_cty, "Liberia","430")
asarray(hl_cty, "Libya","434")
asarray(hl_cty, "Liechtenstein","438")
asarray(hl_cty, "Lithuania","440")
asarray(hl_cty, "Luxembourg","442")
asarray(hl_cty, "Macau","446")
asarray(hl_cty, "Madagascar","450")
asarray(hl_cty, "Malawi","454")
asarray(hl_cty, "Malaysia","458")
asarray(hl_cty, "Maldives","462")
asarray(hl_cty, "Mali","466")
asarray(hl_cty, "Malta","470")
asarray(hl_cty, "Martinique","474")
asarray(hl_cty, "Mauritania","478")
asarray(hl_cty, "Mauritius","480")
asarray(hl_cty, "Mexico","484")
asarray(hl_cty, "Monaco","492")
asarray(hl_cty, "Mongolia","496")
asarray(hl_cty, "Moldova","498")
asarray(hl_cty, "Montenegro","499")
asarray(hl_cty, "Montserrat","500")
asarray(hl_cty, "Morocco","504")
asarray(hl_cty, "Mozambique","508")
asarray(hl_cty, "Oman","512")
asarray(hl_cty, "Namibia","516")
asarray(hl_cty, "Nauru","520")
asarray(hl_cty, "Nepal","524")
asarray(hl_cty, "Netherlands","528")
asarray(hl_cty, "CuraASSao","531")
asarray(hl_cty, "Netherlands Antilles (before Aruba split away in 1986)","532")
asarray(hl_cty, "Aruba","533")
asarray(hl_cty, "Caribbean Netherlands","535")
asarray(hl_cty, "New Caledonia","540")
asarray(hl_cty, "Vanuatu","548")
asarray(hl_cty, "New Zealand","554")
asarray(hl_cty, "Nicaragua","558")
asarray(hl_cty, "Niger","562")
asarray(hl_cty, "Nigeria","566")
asarray(hl_cty, "Norway","578")
asarray(hl_cty, "Northern Mariana Islands","580")
asarray(hl_cty, "Trust Territory of the Pacific Islands","582")
asarray(hl_cty, "Federated States of Micronesia","583")
asarray(hl_cty, "Marshall Islands","584")
asarray(hl_cty, "Palau","585")
asarray(hl_cty, "Pakistan","586")
asarray(hl_cty, "Panama","591")
asarray(hl_cty, "Panama Canal Zone","594")
asarray(hl_cty, "Papua New Guinea","598")
asarray(hl_cty, "Paraguay","600")
asarray(hl_cty, "Peru","604")
asarray(hl_cty, "Philippines","608")
asarray(hl_cty, "Pitcairn Islands","612")
asarray(hl_cty, "Poland","616")
asarray(hl_cty, "Portugal","620")
asarray(hl_cty, "Guinea-Bissau","624")
asarray(hl_cty, "East Timor","626")
asarray(hl_cty, "Puerto Rico","630")
asarray(hl_cty, "Qatar","634")
asarray(hl_cty, "Reunion","638")
asarray(hl_cty, "Romania","642")
asarray(hl_cty, "Rwanda","646")
asarray(hl_cty, "Saint Helena (Ascension and Tristan da Cunha)","654")
asarray(hl_cty, "Anguilla","660")
asarray(hl_cty, "Saint Lucia","662")
asarray(hl_cty, "Collectivity of Saint Martin","663")
asarray(hl_cty, "Saint Pierre and Miquelon","666")
asarray(hl_cty, "Saint Vincent and the Grenadines","670")
asarray(hl_cty, "San Marino","674")
asarray(hl_cty, "SAPSo Tome and PrAncipe","678")
asarray(hl_cty, "Saudi Arabia","682")
asarray(hl_cty, "Senegal","686")
asarray(hl_cty, "Seychelles","690")
asarray(hl_cty, "Sierra Leone","694")
asarray(hl_cty, "Sikkim","698")
asarray(hl_cty, "Singapore","702")
asarray(hl_cty, "Slovakia","703")
asarray(hl_cty, "Vietnam","704")
asarray(hl_cty, "Slovenia","705")
asarray(hl_cty, "Somalia","706")
asarray(hl_cty, "South Africa","710")
asarray(hl_cty, "Zimbabwe","716")
asarray(hl_cty, "Spain","724")
asarray(hl_cty, "South Sudan","728")
asarray(hl_cty, "Sudan","729")
asarray(hl_cty, "Western Sahara","732")
asarray(hl_cty, "Suriname","740")
asarray(hl_cty, "Svalbard and Jan Mayen","744")
asarray(hl_cty, "Swaziland","748")
asarray(hl_cty, "Sweden","752")
asarray(hl_cty, "Switzerland","756")
asarray(hl_cty, "Syria","760")
asarray(hl_cty, "Tajikistan","762")
asarray(hl_cty, "Thailand","764")
asarray(hl_cty, "Togo","768")
asarray(hl_cty, "Tokelau","772")
asarray(hl_cty, "Tonga","776")
asarray(hl_cty, "Trinidad and Tobago","780")
asarray(hl_cty, "United Arab Emirates","784")
asarray(hl_cty, "Tunisia","788")
asarray(hl_cty, "Turkey","792")
asarray(hl_cty, "Turkmenistan","795")
asarray(hl_cty, "Tuvalu","798")
asarray(hl_cty, "Uganda","800")
asarray(hl_cty, "Ukraine","804")
asarray(hl_cty, "Soviet Union","810")
asarray(hl_cty, "Egypt","818")
asarray(hl_cty, "United Kingdom","826")
asarray(hl_cty, "Guernsey","831")
asarray(hl_cty, "Jersey","832")
asarray(hl_cty, "Isle of Man","833")
asarray(hl_cty, "Tanzania","834")
asarray(hl_cty, "United States","840")
asarray(hl_cty, "United States Miscellaneous Pacific Islands","849")
asarray(hl_cty, "United States Virgin Islands","850")
asarray(hl_cty, "Burkina Faso","854")
asarray(hl_cty, "Uruguay","858")
asarray(hl_cty, "Uzbekistan","860")
asarray(hl_cty, "Venezuela","862")
asarray(hl_cty, "Wake Island","872")
asarray(hl_cty, "Samoa","882")
asarray(hl_cty, "Yemen","887")
asarray(hl_cty, "Socialist Federal Republic of Yugoslavia","890")
asarray(hl_cty, "Zambia","894")
asarray(hl_cty, "Tibet","895")

}

mata mosave loadcty(), dir(~\Documents\GitHub\APIPackages\Stata\utils) replace
        end


